const assert=require('node:assert/strict');
const {derive}=require('./level2_state_view');
const {matches}=require('./level2_state_view');
const example={level:-3,viewDelta:2,weighted:-1,priceReturn:4,amount:3e8,amountChange:10,status:'AVAILABLE',streak:3,sign:-1,improve:2,history:[{amount:100,net:1,ratio:1},{amount:100,net:-3,ratio:-3}]};
assert.equal(matches(example,{preset:'relief',amountMin:2,price:'positive',coverage:'full',sellDays:3,turn:'toSell'}),true);
assert.equal(matches(example,{preset:'buyStrong'}),false);
assert.equal(matches(example,{amountMax:2}),false);
assert.equal(matches(example,{buyDays:1}),false);
assert.equal(matches({...example,weighted:null},{preset:'upSell'}),false);
assert.equal(matches({...example,viewDelta:null},{deltaMin:0}),false);
assert.equal(matches({...example,history:[example.history[1]]},{turn:'sell'}),false);
assert.equal(matches(example,{weightedMin:-1,weightedMax:-1}),true);
const row=(day,amount,ratio)=>({day,amount,ratio,net:ratio===null?null:amount*ratio/100,unknown:ratio===null?amount:0});
const state=history=>({history});
const result={day:'20260922',window:2,states:{A:state([row('20260921',100,-10),row('20260922',100,10)]),B:state([row('20260921',900,20),row('20260922',900,10)]),C:state([row('20260921',50,null),row('20260922',50,5)])}};
const v=derive(result);
assert.equal(v.common,2);assert.equal(v.trajectory[0].ratio,17);assert.equal(v.trajectory[0].amountCoverage,3);
assert.equal(v.trajectory[0].directionCoverage,2);assert.equal(v.trajectory[0].commonAmount,1000);assert.equal(v.trajectory[1].ratioDeltaPP,-7);
assert.deepEqual(v.marketState.ratioPersistence,{side:1,days:2,leftCensored:true});assert.deepEqual(v.marketState.breadthPersistence,{side:1,days:1,leftCensored:false});
assert.deepEqual(v.counts,{improve:1,worsen:1,flat:0,unknown:1,toBuy:1,toSell:0});
assert.equal(v.trajectory[1].buyShare,100);
assert.equal(derive({...result,states:{C:result.states.C}}).trajectory[0].ratio,null);
assert.equal(derive({...result,states:{C:result.states.C}}).marketState.status,'NO_COMMON_COHORT');
const one=derive({window:1,states:{A:state([row('20260922',100,1)])}});assert.equal(one.applicable,false);assert.equal(one.marketState.ratioDeltaPP,null);assert.equal(one.marketState.ratioImprovement.comparisons,null);
const tiny=derive({window:2,states:{A:state([row('1',100,1),row('2',100,1.0000001)])}});
assert.equal(tiny.stocks[0].change,'improve');
assert.equal(derive({window:2,states:{}}).common,0);
const priceView=derive({window:2,states:{A:state([{...row('1',100,-1),priceDailyReturn:5},{...row('2',100,-1),priceDailyReturn:-1}]),B:state([{...row('1',100,1),priceDailyReturn:0},{...row('2',100,1),priceDailyReturn:2}]),C:state([{...row('1',100,null),priceDailyReturn:4},{...row('2',100,1),priceDailyReturn:null}])}});
assert.equal(priceView.priceCommon,2);assert.deepEqual(priceView.trajectory.map(r=>r.priceCoverage),[3,2]);assert.deepEqual(priceView.trajectory.map(r=>r.priceUpShare),[50,50]);assert.equal(priceView.priceState.upShareSlopePPPerDay,0);
assert.equal(derive({window:2,states:{A:state([row('1',100,1),row('2',100,1)])}}).counts.flat,1);
console.log('state view: weighted/cohort/missing/unknown/one-day/transitions/tiny/empty/flat PASS');
